[package]
name = "try-nvcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.17", features = ["cuda-12060"] }
zstd = "0.13"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8"
bytesize = "1.3"

[build-dependencies]
bindgen = "0.70"
cc = "1.0"
